config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects, only: [:index, :show, :new, :create] do 
    resources :rewards, only: [:new, :create, :show, :destroy] 
  end

  resources :users, only: [:new, :edit, :create, :show] 
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :pledges 

  get 'login' => 'user_sessions#new', as: 'login'
  get "logout" => 'user_sessions#destroy', as: 'logout'

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :reward
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :owner, class_name: "User"

	has_many :pledges
  has_many :backers, through: :pledges, source: :user

	has_many :rewards
	
	accepts_nested_attributes_for :rewards
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project

  has_many :pledges

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  has_many :owned_projects, class_name: "Project", foreign_key: "owner_id"

  has_many :pledges
  has_many :backed_projects, through: :pledges, source: :project

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	def not_authenticated
		redirect_to login_path, alert: "please log in"
	end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	def new
		@pledge = Pledge.new
	end

	def create
    	@pledge = Pledge.new(pledge_params)
    	@pledge.user_id = current_user.id

	    if @pledge.save
	      redirect_to user_path(current_user)
	    else
	      render :new
	    end
	end

	def edit

	end

	def destroy
		@pledge = Pledge.find(params[:id])
    	@pledge.destroy
	end

	private
    def pledge_params
      params.require(:pledge).permit(:amount, :reward_id, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login, except: :index
  

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
      if @project.save
        redirect_to @project
      else
        render :new
      end
  end

private
  def project_params
    params.require(:project).permit(:title, :description, :start_date, :end_date, :goal, rewards_attributes: [:amount, :description])
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def new
  end

  def create
    @project = Project.find(params[:project_id])
    @reward = @project.rewards.build(reward_params)
    if @reward.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @reward = Reward.find(params[:id])
  end

  def destroy
      @reward = Reward.find(params[:id])
      @reward.destroy
  end

  private
  def reward_params
    params.require(:rewards).permit(:amount, :description, :project_id)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

	def new 

	end

	def create
		if @user = login(params[:email], params[:password], params[:remember_me])
			redirect_back_or_to(root_url, notice: "Login Successful!")
		else 
			flash.now[:alert] = "Login failed!"
			render "new"
		end
	end	

	def destroy
		logout
		redirect_to root_url, notice: "logged out"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		auto_login(@user)
  		redirect_to projects_url, {notice: "Signed up"}
  	else
  		render 'new'
  	end
  end

  def show
    @pledges = current_user.pledges 
  end

  def edit
  	
  end

 private
 def user_params
 	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1 class="navbar-logo"><a href="#">CROWDFUNDER</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><%= link_to "Projects", projects_path %></li>
      <% if current_user %>
        <li class="inactive"><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li class="inactive"><%= link_to "Log In", login_path %></li>
      <% end %>
      <li class="inactive"><%= link_to "Sign In", new_user_path %></li>
      <li class="has-dropdown">
        <a href="#">Menu</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
          <li class="active"><a href="#">Active link in dropdown</a></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body class"<%= controller_name %> <%= action_name %>">

  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>

  <%= render 'layouts/navbar' %>

  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

  <%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/projects/_pledge_field.html.erb
<% @project.rewards.each do |reward| %> 
	
	<h3>Reward</h3>
	<p><%= reward.amount %></p>
	<p><%= reward.description %></p>

	<%= form_for Pledge.new do |f| %>
		<%= f.hidden_field :amount, value: reward.amount %>
		<%= f.hidden_field :reward_id, value: reward.id %>
		<%= f.hidden_field :project_id, value: @project.id %>
		<%= f.submit "Pledge this!" %>
	<% end %>

<% end %>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
	
	<div class="field">
		<%= f.label :amount %> 
		<%= f.text_field :amount %> 
	</div>

	<div class="field">
		<%= f.label :description %> 
		<%= f.text_field :description %> 
	</div>

	<%= link_to_remove_association 'Remove reward', f %>
	
</div>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
	<div class="project-block">
		<h1><%= link_to project.title, project_path(project) %></h1>

		<p><%= project.description %></p>
		<p><%= project.goal %></p>
		<p><%= project.start_date %></p>
		<p><%= project.end_date %></p><br/> 
	</div>
<% end %>

app/views/projects/new.html.erb
<h1>Create a New Project</h1>

<%= form_for (@project) do |f| %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :goal %><br />
		<%= f.number_field :goal %>
	</div>

	<div class="field">
		<%= f.label :start_date %><br />
		<%= f.datetime_select :start_date %>
	</div>

	<div class="field">
		<%= f.label :end_date %><br />
		<%= f.datetime_select :end_date %>
	</div>

	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</div>

	<p><strong>Add Rewards</strong></p>
	
	<div id="rewards">
		<%= f.fields_for :rewards do |r| %>
			<%= render 'reward_fields', :f => r %>
		<% end %> 
		<%= link_to_add_association 'Add a reward', f, :rewards %><br />  
		<%= f.submit %>
	</div>
	
<% end %> 

app/views/projects/show.html.erb
<h1><%= @project.title %></h1><br />

<p><%= @project.description %></p>
<p>$ <%= @project.goal %></p>
<p><%= @project.start_date %></p>
<p><%= @project.end_date %></p> 

<div>
	<%= render 'pledge_field' %>
</div><br />



<%= link_to 'back', projects_url %>

app/views/rewards/create.html.erb
<h1>Rewards#create</h1>
<p>Find me in app/views/rewards/create.html.erb</p>

app/views/rewards/new.html.erb
<h1>Rewards#new</h1>
<p>Find me in app/views/rewards/new.html.erb</p>

app/views/rewards/show.html.erb
<h1>Rewards#show</h1>
<p>Find me in app/views/rewards/show.html.erb</p>

app/views/user_sessions/new.html.erb
<h2>Log in</h2>

<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div class="field">
    <%= check_box_tag :remember_me %><br />
    <%= label_tag :remember_me %>
  </div>

  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<div class="field">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name %>
	</div>

	<div class="field">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name %>
	</div>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="field">
		<%= f.submit %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %> 

app/views/users/show.html.erb
<% @pledges.each do |pledge| %>

	<p><%= pledge.amount %></p>
	<p><%= pledge.reward.description %></p>

<% end %>